version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: themosis-web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: themosis
      WORDPRESS_DB_USER: themosis
      WORDPRESS_DB_PASSWORD: themosis
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: themosis-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: themosis
      MYSQL_USER: themosis
      MYSQL_PASSWORD: themosis
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
